### PR TITLE
MSEARCH-86: Remove not required env variables from module descriptor.

### PR DESCRIPTION
**Pull request by bohdan-suprun**
> Ok, if my assumptions are correct and deployment tool copies env variables from module descriptor as they are, than the quickest fix is to leave only those variables that will be overridden by OKAPI: DB connection properties and remove all other properties.

### CODE REVIEW

**Review by hjiebsco — COMMENTED** [review]
I do not know the reason to remove these env vars, but when we set up a new module, we usually check the module descriptor to see what's new and add new ones to our deployment configuration. Alternatively, if every module documents the required env vars on README properly, we can use that.

**Comment by bohdan-suprun** [comment]
> I do not know the reason to remove these env vars, but when we set up a new module, we usually check the module descriptor to see what's new and add new ones to our deployment configuration. Alternatively, if every module documents the required env vars on README properly, we can use that.

That's my expectation as well. However, the deployment process seems get the env variables from the descriptor and propagates them to the container as they are. It causes issues in code, e.g. ELASTICSEARCH_URL takes precision over ELACTICSEARCH_HOST/PORT, so that the  hardcoded sample value for ELASTICSEARCH_URL was used.

**Review by pfilippovEPAM — APPROVED** [review]

**Review by hjiebsco — COMMENTED** [review]
It is a bit inconsistent to keep DB and Kafka but remove ES. But I will leave devops team to decide.

**Comment by bohdan-suprun** [comment]
Closing as @funkymalc working on fix from their side.

**Pull request closed without merging**
